### ISSUE TITLE
Code 구현에 대한 주석 형식

### ISSUE THREAD

**Issue by jaewan7599** [19-1-skku-oss/2019-1-OSS-E5#12]
모두가 쉽게 알아보기 위한 주석 형식이 필요할 것 같습니다. 이에 대한 의견 부탁드립니다.

Signed-off-by: jaewan <jaewan7599@skku.edu>

**Comment by nicholas369** [comment]
https://github.com/xpressengine/xe-core/wiki/%EC%BD%94%EB%93%9C-%EB%AC%B8%EC%84%9C%ED%99%94%EB%A5%BC-%EC%9C%84%ED%95%9C-%EC%A3%BC%EC%84%9D-%EA%B7%9C%EC%B9%99(Draft-v0.1)

위 페이지를 참조하여 형식을 일관화시키면 좋을 것 같습니다.

**Comment by pitlover** [comment]
넵 확인했습니다

**Comment by jaewan7599** [comment]
확인하였습니다. 위의 링크를 참고하면 좋을 것 같습니다. Issue를 Close하겠습니다.
