### ISSUE TITLE
commit 관련 질문합니다!

### ISSUE THREAD

**Issue by pitlover** [19-1-skku-oss/2019-1-OSS-E5#13]
![image](https://user-images.githubusercontent.com/49435880/58745203-f4dc2e80-8488-11e9-8814-06e0bd857f9f.png)

제가 3n+1.py push했는데 커밋이 제대로 올라갔는지 확인 부탁드립니다!

**Comment by pitlover** [comment]
+원본 파일 한 번 push하고 수정한 거 계속 올리면 되는 거죠?

**Comment by jaewan7599** [comment]
네 그렇게 하시면 됩니다

**Comment by jaewan7599** [comment]
Pull request를 확인하였으므로, 해당 Issue를 Close하겠습니다. 추가적인 의견이 있으시면 새로운 Issue 부탁드립니다.
