### ISSUE TITLE
새로 생성된 파일 위치

### ISSUE THREAD

**Issue by nicholas369** [19-1-skku-oss/2019-1-OSS-E5#37]
작업이 완료되었다고 생각되는 소스코드들은
추후 원활한 pull request를 위해
Python 디렉토리의 하위 카테고리중
분류에 맞는 곳으로 옮기는 것이 어떨까 건의해봅니다.

**Comment by jaewan7599** [comment]
좋은 의견인 것 같습니다

**Comment by pitlover** [comment]
좋아요
