### ISSUE TITLE
정적페이지 수정

### ISSUE THREAD

**Issue by nicholas369** [19-1-skku-oss/2019-1-OSS-E5#49]
내일부터 정적페이지에 본격적으로 컨텐츠들을 넣을까 하는데

https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages

위 링크를 읽어보니 github page source file을 관리하는 방법이 3가지가 존재합니다.

현재는 publishing source가 master branch로 설정이 되어있는데 

이대로 유지할지, 혹은 다른 건의사항 있으면 오늘까지 건의 바랍니다.

**Comment by Jun-honey** [comment]
1. Default source settings for repositories without the username naming scheme

2. Enabling GitHub Pages to publish your site from master or gh-pages

3. Publishing your GitHub Pages site from a /docs folder on your master branch
중에 2번 말씀 하시는 거죠?

2번 방식을 유지하는 거도 나쁘지 않을꺼 같아요!!
화이팅 하세요!

**Comment by pitlover** [comment]
넵 저도 2번 방식으로 진행하겠습니당~
